// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTKnBvF9JuEJMvvsGxtAE8XQ8u1bS-vI8',
    appId: '1:1535084356:web:5efceb7819d2ac93c3f911',
    messagingSenderId: '1535084356',
    projectId: 'nexo-app-2af2c',
    authDomain: 'nexo-app-2af2c.firebaseapp.com',
    storageBucket: 'nexo-app-2af2c.firebasestorage.app',
    measurementId: 'G-BR4ZQYVVXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_Xci89PxzENhFZSYHBSeVRewSFrPuaHQ',
    appId: '1:1535084356:android:8ccd852472a12467c3f911',
    messagingSenderId: '1535084356',
    projectId: 'nexo-app-2af2c',
    storageBucket: 'nexo-app-2af2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ7okFyuzC4gY6LSfX_XVoKHosFHMfk4U',
    appId: '1:1535084356:ios:f52f6657167533e5c3f911',
    messagingSenderId: '1535084356',
    projectId: 'nexo-app-2af2c',
    storageBucket: 'nexo-app-2af2c.firebasestorage.app',
    iosBundleId: 'com.example.nexo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ7okFyuzC4gY6LSfX_XVoKHosFHMfk4U',
    appId: '1:1535084356:ios:f52f6657167533e5c3f911',
    messagingSenderId: '1535084356',
    projectId: 'nexo-app-2af2c',
    storageBucket: 'nexo-app-2af2c.firebasestorage.app',
    iosBundleId: 'com.example.nexo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTKnBvF9JuEJMvvsGxtAE8XQ8u1bS-vI8',
    appId: '1:1535084356:web:b8c4ec980c500778c3f911',
    messagingSenderId: '1535084356',
    projectId: 'nexo-app-2af2c',
    authDomain: 'nexo-app-2af2c.firebaseapp.com',
    storageBucket: 'nexo-app-2af2c.firebasestorage.app',
    measurementId: 'G-DZSL7GF587',
  );
}
